hydra:
  run:
    dir: .

# model_path: "Qwen/Qwen2.5-7B-Instruct"
# model_path: "/mnt/user/models/Llama-3.1-8B-Instruct"
model_path: "gpt-4o-mini"

dp_size: 4
tp_size: 1
model_name: ${get_last_segment:${model_path}}

batch_size: 128

max_new_tokens: 256

# calibration
recompute_calibration: true
calibration_file: "gsm8k/${model_name}/calibration.json"
calibration_sample_size: 1000
enable_calibrate: true

# results
results_file: "gsm8k/${model_name}/results.json"

# debug mode
debug: false
sample_size: 3

# openai
num_threads: 200
